import {
  Sparkles,
  Wand2,
  Save,
  Upload,
  Check,
  Github,
  FolderOpen,
  Play,
  Coins,
  Gamepad2,
  MessageSquare,
  AlertTriangle,
} from 'lucide-react';

export const creatorArenaTour = {
  id: 'creatorArena',
  name: 'CreatorArena Tour',
  version: 2,
  requiredPath: '/create',
  steps: [
    {
      id: 'alpha-warning',
      target: '[data-tour-step="creator-alpha-badge"]',
      position: 'bottom',
      icon: AlertTriangle,
      title: 'Alpha Testing',
      subtitle: 'Work in progress',
      content: 'CreatorArena is still in alpha testing. You may encounter bugs or unexpected behavior. We\'re actively improving it, and your feedback helps!',
      tip: 'Report issues via the feedback button or Discord.',
      spotlightPadding: 8,
    },
    {
      id: 'welcome',
      target: '[data-tour-step="creator-header"]',
      position: 'bottom',
      icon: Sparkles,
      title: 'Welcome to CreatorArena',
      subtitle: 'Build games with AI',
      content: 'CreatorArena lets you describe a game in plain English and generate a fully playable version with AI. Let\'s walk through the key controls.',
      tip: 'Use Next to step through, or Skip to dismiss.',
      spotlightPadding: 2,
    },
    {
      id: 'credits',
      target: '[data-tour-step="creator-credits"]',
      position: 'bottom',
      icon: Coins,
      title: 'Your Credits',
      subtitle: 'Track your balance',
      content: 'Each AI game generation or revision costs credits. Your balance and the exact cost appear before you create.',
      spotlightPadding: 8,
    },
    {
      id: 'game-title',
      target: '[data-tour-step="creator-game-title"]',
      position: 'right',
      icon: Gamepad2,
      title: 'Game Title & Description',
      subtitle: 'Name your creation',
      content: 'Give your game a title and short description. These are shown in the gallery when you publish.',
      spotlightPadding: 6,
    },
    {
      id: 'prompt-input',
      target: '[data-tour-step="creator-prompt"]',
      position: 'right',
      icon: MessageSquare,
      title: 'Describe Your Game',
      subtitle: 'The more detail, the better',
      content: 'Type a detailed description of the game you want: mechanics, graphics, controls, and story. Minimum 10 words. You can also generate a sample prompt for inspiration.',
      tip: 'Be specific! "A retro space shooter with power-ups and neon graphics" works better than just "a game".',
      spotlightPadding: 6,
    },
    {
      id: 'generate-button',
      target: '[data-tour-step="creator-generate"]',
      position: 'right',
      icon: Wand2,
      title: 'Generate Your Game',
      subtitle: 'AI does the building',
      content: 'Hit this button to generate your game from the prompt. The AI will create a fully playable HTML game. You can regenerate or revise it after.',
      spotlightPadding: 6,
    },
    {
      id: 'preview',
      target: '[data-tour-step="creator-preview"]',
      position: 'left',
      icon: Play,
      title: 'Live Preview',
      subtitle: 'Play your game instantly',
      content: 'Your generated game appears here in a live preview. You can play it, test it, and see changes in real-time.',
      spotlightPadding: 4,
    },
    {
      id: 'save-button',
      target: '[data-tour-step="creator-save"]',
      position: 'bottom',
      icon: Save,
      title: 'Save Your Game',
      subtitle: 'Don\'t lose your work',
      content: 'Save your game to keep your progress. You\'ll get a reminder after generating. Make sure to save before navigating away!',
      spotlightPadding: 8,
    },
    {
      id: 'verify-button',
      target: '[data-tour-step="creator-verify"]',
      position: 'bottom',
      icon: Check,
      title: 'Verify Your Game',
      subtitle: 'Quality check before publishing',
      content: 'Verification runs an AI check on your game to make sure it\'s playable and meets quality standards. Required before publishing.',
      spotlightPadding: 8,
    },
    {
      id: 'publish-button',
      target: '[data-tour-step="creator-publish"]',
      position: 'bottom',
      icon: Upload,
      title: 'Publish to Gallery',
      subtitle: 'Share with the world',
      content: 'Once verified, publish your game to the public gallery where other players can discover and play it.',
      spotlightPadding: 8,
    },
    {
      id: 'my-games',
      target: '[data-tour-step="creator-my-games"]',
      position: 'bottom',
      icon: FolderOpen,
      title: 'My Games',
      subtitle: 'Manage your creations',
      content: 'Access all your saved games here. Load any previous game to continue editing or make revisions.',
      spotlightPadding: 8,
    },
    {
      id: 'push-github',
      target: '[data-tour-step="creator-push"]',
      position: 'bottom',
      icon: Github,
      title: 'Push to GitHub',
      subtitle: 'Export your code',
      content: 'Push your game\'s source code to GitHub. Great for sharing, hosting elsewhere, or continuing development.',
      spotlightPadding: 8,
    },
  ],
};
