import {
  Sparkles,
  Swords,
  Target,
  Trophy,
  Users,
  MessageSquare,
  TrendingUp,
} from 'lucide-react';

export const siteTour = {
  id: 'site',
  name: 'CodeArena Welcome Tour',
  version: 1,
  requiredPath: '/', // Start on homepage
  steps: [
    {
      id: 'welcome',
      target: '[data-tour-step="hero-section"]',
      position: 'bottom',
      icon: Sparkles,
      title: 'Welcome to CodeArena!',
      subtitle: 'Your competitive coding journey starts here',
      content: 'CodeArena is where developers battle head-to-head in real-time coding challenges. Let\'s take a quick tour of everything you can do here.',
      tip: 'This tour takes about 2-3 minutes. Use arrow keys to navigate.',
      spotlightPadding: 20,
    },
    {
      id: 'practice-mode',
      target: '[data-tour-step="practice-link"]',
      position: 'right',
      icon: Target,
      title: 'Practice Mode',
      subtitle: 'Train at your own pace',
      content: 'Sharpen your skills without pressure. Quick original problems in JavaScript, Python, and TypeScript. Perfect for warming up before ranked battles.',
      tip: 'Pro tip: Practice problems help you learn patterns that appear in battles.',
      spotlightPadding: 8,
    },
    {
      id: 'matchmaking',
      target: '[data-tour-step="start-battle-btn"]',
      position: 'right',
      icon: Swords,
      title: 'Start a Battle',
      subtitle: 'Compete for ELO rating',
      content: 'Enter the matchmaking queue to face an opponent at your skill level. Both players get the same problem - first correct solution wins!',
      spotlightPadding: 8,
    },
    {
      id: 'leaderboard',
      target: '[data-tour-step="leaderboard-section"]',
      position: 'top',
      icon: Trophy,
      title: 'Climb the Ranks',
      subtitle: 'Bronze → Grandmaster',
      content: 'Win battles to increase your ELO rating and climb the global leaderboard. Track your progress against the top coders worldwide.',
      tip: 'Ranks: Bronze, Silver, Gold, Platinum, Diamond, Master, Grandmaster',
      spotlightPadding: 12,
    },
    {
      id: 'friends',
      target: '[data-tour-step="nav-friends"]',
      position: 'bottom',
      icon: Users,
      title: 'Friends & Challenges',
      subtitle: 'Build your network',
      content: 'Add friends to challenge them directly to private battles. See when friends are online and track their progress.',
      spotlightPadding: 8,
    },
    {
      id: 'messages',
      target: '[data-tour-step="nav-messages"]',
      position: 'bottom',
      icon: MessageSquare,
      title: 'Messages',
      subtitle: 'Stay connected',
      content: 'Chat with friends, discuss strategies, and coordinate battles. Direct messages and group chats supported.',
      spotlightPadding: 8,
    },
    {
      id: 'profile',
      target: '[data-tour-step="nav-profile"]',
      position: 'bottom',
      icon: TrendingUp,
      title: 'Your Profile',
      subtitle: 'Track your progress',
      content: 'View your stats, battle history, and achievements. See your rating over time and identify areas for improvement.',
      spotlightPadding: 8,
    },
  ],
  onComplete: null,
  onSkip: null,
};
