// Avatar configuration - single source of truth for all avatar data

// Full avatar list with categories (used by avatar pickers)
export const AVATARS = [
  { id: 'default-1', category: 'Default', emoji: '⭐' },
  { id: 'default-2', category: 'Default', emoji: '🔵' },
  { id: 'default-3', category: 'Default', emoji: '🟣' },
  { id: 'default-4', category: 'Default', emoji: '🔶' },
  { id: 'default-5', category: 'Default', emoji: '✨' },
  { id: 'gaming-1', category: 'Gaming', emoji: '🎮' },
  { id: 'gaming-2', category: 'Gaming', emoji: '🕹️' },
  { id: 'gaming-3', category: 'Gaming', emoji: '👾' },
  { id: 'gaming-4', category: 'Gaming', emoji: '🤖' },
  { id: 'gaming-5', category: 'Gaming', emoji: '🎯' },
  { id: 'gaming-6', category: 'Gaming', emoji: '🏆' },
  { id: 'gaming-7', category: 'Gaming', emoji: '⚔️' },
  { id: 'gaming-8', category: 'Gaming', emoji: '🛡️' },
  { id: 'gaming-9', category: 'Gaming', emoji: '🔮' },
  { id: 'gaming-10', category: 'Gaming', emoji: '🌟' },
  { id: 'dev-1', category: 'Developer', emoji: '💻' },
  { id: 'dev-2', category: 'Developer', emoji: '⌨️' },
  { id: 'dev-3', category: 'Developer', emoji: '🖥️' },
  { id: 'dev-4', category: 'Developer', emoji: '📱' },
  { id: 'dev-5', category: 'Developer', emoji: '🚀' },
  { id: 'dev-6', category: 'Developer', emoji: '⚡' },
  { id: 'dev-7', category: 'Developer', emoji: '🔧' },
  { id: 'dev-8', category: 'Developer', emoji: '🐛' },
  { id: 'dev-9', category: 'Developer', emoji: '☕' },
  { id: 'dev-10', category: 'Developer', emoji: '🦾' },
  { id: 'animal-1', category: 'Animals', emoji: '🐱' },
  { id: 'animal-2', category: 'Animals', emoji: '🐶' },
  { id: 'animal-3', category: 'Animals', emoji: '🦊' },
  { id: 'animal-4', category: 'Animals', emoji: '🐼' },
  { id: 'animal-5', category: 'Animals', emoji: '🦁' },
  { id: 'animal-6', category: 'Animals', emoji: '🐯' },
  { id: 'animal-7', category: 'Animals', emoji: '🐻' },
  { id: 'animal-8', category: 'Animals', emoji: '🦄' },
  { id: 'animal-9', category: 'Animals', emoji: '🐸' },
  { id: 'animal-10', category: 'Animals', emoji: '🦉' },
  { id: 'face-1', category: 'Faces', emoji: '😎' },
  { id: 'face-2', category: 'Faces', emoji: '🤓' },
  { id: 'face-3', category: 'Faces', emoji: '🥳' },
  { id: 'face-4', category: 'Faces', emoji: '😈' },
  { id: 'face-5', category: 'Faces', emoji: '👻' },
  { id: 'face-6', category: 'Faces', emoji: '🥷' },
  { id: 'face-7', category: 'Faces', emoji: '🧙' },
  { id: 'face-8', category: 'Faces', emoji: '🤠' },
  { id: 'face-9', category: 'Faces', emoji: '💀' },
  { id: 'face-10', category: 'Faces', emoji: '👽' },
  { id: 'flag-af', category: 'Flags', emoji: '🇦🇫' },
  { id: 'flag-al', category: 'Flags', emoji: '🇦🇱' },
  { id: 'flag-dz', category: 'Flags', emoji: '🇩🇿' },
  { id: 'flag-ad', category: 'Flags', emoji: '🇦🇩' },
  { id: 'flag-ao', category: 'Flags', emoji: '🇦🇴' },
  { id: 'flag-ag', category: 'Flags', emoji: '🇦🇬' },
  { id: 'flag-ar', category: 'Flags', emoji: '🇦🇷' },
  { id: 'flag-am', category: 'Flags', emoji: '🇦🇲' },
  { id: 'flag-au', category: 'Flags', emoji: '🇦🇺' },
  { id: 'flag-at', category: 'Flags', emoji: '🇦🇹' },
  { id: 'flag-az', category: 'Flags', emoji: '🇦🇿' },
  { id: 'flag-bs', category: 'Flags', emoji: '🇧🇸' },
  { id: 'flag-bh', category: 'Flags', emoji: '🇧🇭' },
  { id: 'flag-bd', category: 'Flags', emoji: '🇧🇩' },
  { id: 'flag-bb', category: 'Flags', emoji: '🇧🇧' },
  { id: 'flag-by', category: 'Flags', emoji: '🇧🇾' },
  { id: 'flag-be', category: 'Flags', emoji: '🇧🇪' },
  { id: 'flag-bz', category: 'Flags', emoji: '🇧🇿' },
  { id: 'flag-bj', category: 'Flags', emoji: '🇧🇯' },
  { id: 'flag-bt', category: 'Flags', emoji: '🇧🇹' },
  { id: 'flag-bo', category: 'Flags', emoji: '🇧🇴' },
  { id: 'flag-ba', category: 'Flags', emoji: '🇧🇦' },
  { id: 'flag-bw', category: 'Flags', emoji: '🇧🇼' },
  { id: 'flag-br', category: 'Flags', emoji: '🇧🇷' },
  { id: 'flag-bn', category: 'Flags', emoji: '🇧🇳' },
  { id: 'flag-bg', category: 'Flags', emoji: '🇧🇬' },
  { id: 'flag-bf', category: 'Flags', emoji: '🇧🇫' },
  { id: 'flag-bi', category: 'Flags', emoji: '🇧🇮' },
  { id: 'flag-cv', category: 'Flags', emoji: '🇨🇻' },
  { id: 'flag-kh', category: 'Flags', emoji: '🇰🇭' },
  { id: 'flag-cm', category: 'Flags', emoji: '🇨🇲' },
  { id: 'flag-ca', category: 'Flags', emoji: '🇨🇦' },
  { id: 'flag-cf', category: 'Flags', emoji: '🇨🇫' },
  { id: 'flag-td', category: 'Flags', emoji: '🇹🇩' },
  { id: 'flag-cl', category: 'Flags', emoji: '🇨🇱' },
  { id: 'flag-cn', category: 'Flags', emoji: '🇨🇳' },
  { id: 'flag-co', category: 'Flags', emoji: '🇨🇴' },
  { id: 'flag-km', category: 'Flags', emoji: '🇰🇲' },
  { id: 'flag-cg', category: 'Flags', emoji: '🇨🇬' },
  { id: 'flag-cd', category: 'Flags', emoji: '🇨🇩' },
  { id: 'flag-cr', category: 'Flags', emoji: '🇨🇷' },
  { id: 'flag-ci', category: 'Flags', emoji: '🇨🇮' },
  { id: 'flag-hr', category: 'Flags', emoji: '🇭🇷' },
  { id: 'flag-cu', category: 'Flags', emoji: '🇨🇺' },
  { id: 'flag-cy', category: 'Flags', emoji: '🇨🇾' },
  { id: 'flag-cz', category: 'Flags', emoji: '🇨🇿' },
  { id: 'flag-dk', category: 'Flags', emoji: '🇩🇰' },
  { id: 'flag-dj', category: 'Flags', emoji: '🇩🇯' },
  { id: 'flag-dm', category: 'Flags', emoji: '🇩🇲' },
  { id: 'flag-do', category: 'Flags', emoji: '🇩🇴' },
  { id: 'flag-ec', category: 'Flags', emoji: '🇪🇨' },
  { id: 'flag-eg', category: 'Flags', emoji: '🇪🇬' },
  { id: 'flag-sv', category: 'Flags', emoji: '🇸🇻' },
  { id: 'flag-gq', category: 'Flags', emoji: '🇬🇶' },
  { id: 'flag-er', category: 'Flags', emoji: '🇪🇷' },
  { id: 'flag-ee', category: 'Flags', emoji: '🇪🇪' },
  { id: 'flag-sz', category: 'Flags', emoji: '🇸🇿' },
  { id: 'flag-et', category: 'Flags', emoji: '🇪🇹' },
  { id: 'flag-fj', category: 'Flags', emoji: '🇫🇯' },
  { id: 'flag-fi', category: 'Flags', emoji: '🇫🇮' },
  { id: 'flag-fr', category: 'Flags', emoji: '🇫🇷' },
  { id: 'flag-ga', category: 'Flags', emoji: '🇬🇦' },
  { id: 'flag-gm', category: 'Flags', emoji: '🇬🇲' },
  { id: 'flag-ge', category: 'Flags', emoji: '🇬🇪' },
  { id: 'flag-de', category: 'Flags', emoji: '🇩🇪' },
  { id: 'flag-gh', category: 'Flags', emoji: '🇬🇭' },
  { id: 'flag-gr', category: 'Flags', emoji: '🇬🇷' },
  { id: 'flag-gd', category: 'Flags', emoji: '🇬🇩' },
  { id: 'flag-gt', category: 'Flags', emoji: '🇬🇹' },
  { id: 'flag-gn', category: 'Flags', emoji: '🇬🇳' },
  { id: 'flag-gw', category: 'Flags', emoji: '🇬🇼' },
  { id: 'flag-gy', category: 'Flags', emoji: '🇬🇾' },
  { id: 'flag-ht', category: 'Flags', emoji: '🇭🇹' },
  { id: 'flag-hn', category: 'Flags', emoji: '🇭🇳' },
  { id: 'flag-hu', category: 'Flags', emoji: '🇭🇺' },
  { id: 'flag-is', category: 'Flags', emoji: '🇮🇸' },
  { id: 'flag-in', category: 'Flags', emoji: '🇮🇳' },
  { id: 'flag-id', category: 'Flags', emoji: '🇮🇩' },
  { id: 'flag-ir', category: 'Flags', emoji: '🇮🇷' },
  { id: 'flag-iq', category: 'Flags', emoji: '🇮🇶' },
  { id: 'flag-ie', category: 'Flags', emoji: '🇮🇪' },
  { id: 'flag-il', category: 'Flags', emoji: '🇮🇱' },
  { id: 'flag-it', category: 'Flags', emoji: '🇮🇹' },
  { id: 'flag-jm', category: 'Flags', emoji: '🇯🇲' },
  { id: 'flag-jp', category: 'Flags', emoji: '🇯🇵' },
  { id: 'flag-jo', category: 'Flags', emoji: '🇯🇴' },
  { id: 'flag-kz', category: 'Flags', emoji: '🇰🇿' },
  { id: 'flag-ke', category: 'Flags', emoji: '🇰🇪' },
  { id: 'flag-ki', category: 'Flags', emoji: '🇰🇮' },
  { id: 'flag-kp', category: 'Flags', emoji: '🇰🇵' },
  { id: 'flag-kr', category: 'Flags', emoji: '🇰🇷' },
  { id: 'flag-kw', category: 'Flags', emoji: '🇰🇼' },
  { id: 'flag-kg', category: 'Flags', emoji: '🇰🇬' },
  { id: 'flag-la', category: 'Flags', emoji: '🇱🇦' },
  { id: 'flag-lv', category: 'Flags', emoji: '🇱🇻' },
  { id: 'flag-lb', category: 'Flags', emoji: '🇱🇧' },
  { id: 'flag-ls', category: 'Flags', emoji: '🇱🇸' },
  { id: 'flag-lr', category: 'Flags', emoji: '🇱🇷' },
  { id: 'flag-ly', category: 'Flags', emoji: '🇱🇾' },
  { id: 'flag-li', category: 'Flags', emoji: '🇱🇮' },
  { id: 'flag-lt', category: 'Flags', emoji: '🇱🇹' },
  { id: 'flag-lu', category: 'Flags', emoji: '🇱🇺' },
  { id: 'flag-mg', category: 'Flags', emoji: '🇲🇬' },
  { id: 'flag-mw', category: 'Flags', emoji: '🇲🇼' },
  { id: 'flag-my', category: 'Flags', emoji: '🇲🇾' },
  { id: 'flag-mv', category: 'Flags', emoji: '🇲🇻' },
  { id: 'flag-ml', category: 'Flags', emoji: '🇲🇱' },
  { id: 'flag-mt', category: 'Flags', emoji: '🇲🇹' },
  { id: 'flag-mh', category: 'Flags', emoji: '🇲🇭' },
  { id: 'flag-mr', category: 'Flags', emoji: '🇲🇷' },
  { id: 'flag-mu', category: 'Flags', emoji: '🇲🇺' },
  { id: 'flag-mx', category: 'Flags', emoji: '🇲🇽' },
  { id: 'flag-fm', category: 'Flags', emoji: '🇫🇲' },
  { id: 'flag-md', category: 'Flags', emoji: '🇲🇩' },
  { id: 'flag-mc', category: 'Flags', emoji: '🇲🇨' },
  { id: 'flag-mn', category: 'Flags', emoji: '🇲🇳' },
  { id: 'flag-me', category: 'Flags', emoji: '🇲🇪' },
  { id: 'flag-ma', category: 'Flags', emoji: '🇲🇦' },
  { id: 'flag-mz', category: 'Flags', emoji: '🇲🇿' },
  { id: 'flag-mm', category: 'Flags', emoji: '🇲🇲' },
  { id: 'flag-na', category: 'Flags', emoji: '🇳🇦' },
  { id: 'flag-nr', category: 'Flags', emoji: '🇳🇷' },
  { id: 'flag-np', category: 'Flags', emoji: '🇳🇵' },
  { id: 'flag-nl', category: 'Flags', emoji: '🇳🇱' },
  { id: 'flag-nz', category: 'Flags', emoji: '🇳🇿' },
  { id: 'flag-ni', category: 'Flags', emoji: '🇳🇮' },
  { id: 'flag-ne', category: 'Flags', emoji: '🇳🇪' },
  { id: 'flag-ng', category: 'Flags', emoji: '🇳🇬' },
  { id: 'flag-mk', category: 'Flags', emoji: '🇲🇰' },
  { id: 'flag-no', category: 'Flags', emoji: '🇳🇴' },
  { id: 'flag-om', category: 'Flags', emoji: '🇴🇲' },
  { id: 'flag-pk', category: 'Flags', emoji: '🇵🇰' },
  { id: 'flag-pw', category: 'Flags', emoji: '🇵🇼' },
  { id: 'flag-ps', category: 'Flags', emoji: '🇵🇸' },
  { id: 'flag-pa', category: 'Flags', emoji: '🇵🇦' },
  { id: 'flag-pg', category: 'Flags', emoji: '🇵🇬' },
  { id: 'flag-py', category: 'Flags', emoji: '🇵🇾' },
  { id: 'flag-pe', category: 'Flags', emoji: '🇵🇪' },
  { id: 'flag-ph', category: 'Flags', emoji: '🇵🇭' },
  { id: 'flag-pl', category: 'Flags', emoji: '🇵🇱' },
  { id: 'flag-pt', category: 'Flags', emoji: '🇵🇹' },
  { id: 'flag-qa', category: 'Flags', emoji: '🇶🇦' },
  { id: 'flag-ro', category: 'Flags', emoji: '🇷🇴' },
  { id: 'flag-ru', category: 'Flags', emoji: '🇷🇺' },
  { id: 'flag-rw', category: 'Flags', emoji: '🇷🇼' },
  { id: 'flag-kn', category: 'Flags', emoji: '🇰🇳' },
  { id: 'flag-lc', category: 'Flags', emoji: '🇱🇨' },
  { id: 'flag-vc', category: 'Flags', emoji: '🇻🇨' },
  { id: 'flag-ws', category: 'Flags', emoji: '🇼🇸' },
  { id: 'flag-sm', category: 'Flags', emoji: '🇸🇲' },
  { id: 'flag-st', category: 'Flags', emoji: '🇸🇹' },
  { id: 'flag-sa', category: 'Flags', emoji: '🇸🇦' },
  { id: 'flag-sn', category: 'Flags', emoji: '🇸🇳' },
  { id: 'flag-rs', category: 'Flags', emoji: '🇷🇸' },
  { id: 'flag-sc', category: 'Flags', emoji: '🇸🇨' },
  { id: 'flag-sl', category: 'Flags', emoji: '🇸🇱' },
  { id: 'flag-sg', category: 'Flags', emoji: '🇸🇬' },
  { id: 'flag-sk', category: 'Flags', emoji: '🇸🇰' },
  { id: 'flag-si', category: 'Flags', emoji: '🇸🇮' },
  { id: 'flag-sb', category: 'Flags', emoji: '🇸🇧' },
  { id: 'flag-so', category: 'Flags', emoji: '🇸🇴' },
  { id: 'flag-za', category: 'Flags', emoji: '🇿🇦' },
  { id: 'flag-ss', category: 'Flags', emoji: '🇸🇸' },
  { id: 'flag-es', category: 'Flags', emoji: '🇪🇸' },
  { id: 'flag-lk', category: 'Flags', emoji: '🇱🇰' },
  { id: 'flag-sd', category: 'Flags', emoji: '🇸🇩' },
  { id: 'flag-sr', category: 'Flags', emoji: '🇸🇷' },
  { id: 'flag-se', category: 'Flags', emoji: '🇸🇪' },
  { id: 'flag-ch', category: 'Flags', emoji: '🇨🇭' },
  { id: 'flag-sy', category: 'Flags', emoji: '🇸🇾' },
  { id: 'flag-tw', category: 'Flags', emoji: '🇹🇼' },
  { id: 'flag-tj', category: 'Flags', emoji: '🇹🇯' },
  { id: 'flag-tz', category: 'Flags', emoji: '🇹🇿' },
  { id: 'flag-th', category: 'Flags', emoji: '🇹🇭' },
  { id: 'flag-tl', category: 'Flags', emoji: '🇹🇱' },
  { id: 'flag-tg', category: 'Flags', emoji: '🇹🇬' },
  { id: 'flag-to', category: 'Flags', emoji: '🇹🇴' },
  { id: 'flag-tt', category: 'Flags', emoji: '🇹🇹' },
  { id: 'flag-tn', category: 'Flags', emoji: '🇹🇳' },
  { id: 'flag-tr', category: 'Flags', emoji: '🇹🇷' },
  { id: 'flag-tm', category: 'Flags', emoji: '🇹🇲' },
  { id: 'flag-tv', category: 'Flags', emoji: '🇹🇻' },
  { id: 'flag-ug', category: 'Flags', emoji: '🇺🇬' },
  { id: 'flag-ua', category: 'Flags', emoji: '🇺🇦' },
  { id: 'flag-ae', category: 'Flags', emoji: '🇦🇪' },
  { id: 'flag-gb', category: 'Flags', emoji: '🇬🇧' },
  { id: 'flag-us', category: 'Flags', emoji: '🇺🇸' },
  { id: 'flag-uy', category: 'Flags', emoji: '🇺🇾' },
  { id: 'flag-uz', category: 'Flags', emoji: '🇺🇿' },
  { id: 'flag-vu', category: 'Flags', emoji: '🇻🇺' },
  { id: 'flag-va', category: 'Flags', emoji: '🇻🇦' },
  { id: 'flag-ve', category: 'Flags', emoji: '🇻🇪' },
  { id: 'flag-vn', category: 'Flags', emoji: '🇻🇳' },
  { id: 'flag-ye', category: 'Flags', emoji: '🇾🇪' },
  { id: 'flag-zm', category: 'Flags', emoji: '🇿🇲' },
  { id: 'flag-zw', category: 'Flags', emoji: '🇿🇼' },
];

// Quick lookup map for avatar ID -> emoji (derived from AVATARS)
export const AVATAR_EMOJIS = Object.fromEntries(
  AVATARS.map(avatar => [avatar.id, avatar.emoji])
);

// Country names for flag search
export const FLAG_NAMES = {
  'flag-af': 'Afghanistan', 'flag-al': 'Albania', 'flag-dz': 'Algeria', 'flag-ad': 'Andorra',
  'flag-ao': 'Angola', 'flag-ag': 'Antigua Barbuda', 'flag-ar': 'Argentina', 'flag-am': 'Armenia',
  'flag-au': 'Australia', 'flag-at': 'Austria', 'flag-az': 'Azerbaijan', 'flag-bs': 'Bahamas',
  'flag-bh': 'Bahrain', 'flag-bd': 'Bangladesh', 'flag-bb': 'Barbados', 'flag-by': 'Belarus',
  'flag-be': 'Belgium', 'flag-bz': 'Belize', 'flag-bj': 'Benin', 'flag-bt': 'Bhutan',
  'flag-bo': 'Bolivia', 'flag-ba': 'Bosnia Herzegovina', 'flag-bw': 'Botswana', 'flag-br': 'Brazil',
  'flag-bn': 'Brunei', 'flag-bg': 'Bulgaria', 'flag-bf': 'Burkina Faso', 'flag-bi': 'Burundi',
  'flag-cv': 'Cabo Verde Cape Verde', 'flag-kh': 'Cambodia', 'flag-cm': 'Cameroon', 'flag-ca': 'Canada',
  'flag-cf': 'Central African Republic', 'flag-td': 'Chad', 'flag-cl': 'Chile', 'flag-cn': 'China',
  'flag-co': 'Colombia', 'flag-km': 'Comoros', 'flag-cg': 'Congo', 'flag-cd': 'Congo DRC Democratic',
  'flag-cr': 'Costa Rica', 'flag-ci': 'Ivory Coast Cote Ivoire', 'flag-hr': 'Croatia', 'flag-cu': 'Cuba',
  'flag-cy': 'Cyprus', 'flag-cz': 'Czech Czechia', 'flag-dk': 'Denmark', 'flag-dj': 'Djibouti',
  'flag-dm': 'Dominica', 'flag-do': 'Dominican Republic', 'flag-ec': 'Ecuador', 'flag-eg': 'Egypt',
  'flag-sv': 'El Salvador', 'flag-gq': 'Equatorial Guinea', 'flag-er': 'Eritrea', 'flag-ee': 'Estonia',
  'flag-sz': 'Eswatini Swaziland', 'flag-et': 'Ethiopia', 'flag-fj': 'Fiji', 'flag-fi': 'Finland',
  'flag-fr': 'France', 'flag-ga': 'Gabon', 'flag-gm': 'Gambia', 'flag-ge': 'Georgia',
  'flag-de': 'Germany Deutschland', 'flag-gh': 'Ghana', 'flag-gr': 'Greece', 'flag-gd': 'Grenada',
  'flag-gt': 'Guatemala', 'flag-gn': 'Guinea', 'flag-gw': 'Guinea-Bissau', 'flag-gy': 'Guyana',
  'flag-ht': 'Haiti', 'flag-hn': 'Honduras', 'flag-hu': 'Hungary', 'flag-is': 'Iceland',
  'flag-in': 'India', 'flag-id': 'Indonesia', 'flag-ir': 'Iran', 'flag-iq': 'Iraq',
  'flag-ie': 'Ireland', 'flag-il': 'Israel', 'flag-it': 'Italy Italia', 'flag-jm': 'Jamaica',
  'flag-jp': 'Japan Nippon', 'flag-jo': 'Jordan', 'flag-kz': 'Kazakhstan', 'flag-ke': 'Kenya',
  'flag-ki': 'Kiribati', 'flag-kp': 'North Korea DPRK', 'flag-kr': 'South Korea', 'flag-kw': 'Kuwait',
  'flag-kg': 'Kyrgyzstan', 'flag-la': 'Laos', 'flag-lv': 'Latvia', 'flag-lb': 'Lebanon',
  'flag-ls': 'Lesotho', 'flag-lr': 'Liberia', 'flag-ly': 'Libya', 'flag-li': 'Liechtenstein',
  'flag-lt': 'Lithuania', 'flag-lu': 'Luxembourg', 'flag-mg': 'Madagascar', 'flag-mw': 'Malawi',
  'flag-my': 'Malaysia', 'flag-mv': 'Maldives', 'flag-ml': 'Mali', 'flag-mt': 'Malta',
  'flag-mh': 'Marshall Islands', 'flag-mr': 'Mauritania', 'flag-mu': 'Mauritius', 'flag-mx': 'Mexico',
  'flag-fm': 'Micronesia', 'flag-md': 'Moldova', 'flag-mc': 'Monaco', 'flag-mn': 'Mongolia',
  'flag-me': 'Montenegro', 'flag-ma': 'Morocco', 'flag-mz': 'Mozambique', 'flag-mm': 'Myanmar Burma',
  'flag-na': 'Namibia', 'flag-nr': 'Nauru', 'flag-np': 'Nepal', 'flag-nl': 'Netherlands Holland Dutch',
  'flag-nz': 'New Zealand', 'flag-ni': 'Nicaragua', 'flag-ne': 'Niger', 'flag-ng': 'Nigeria',
  'flag-mk': 'North Macedonia', 'flag-no': 'Norway', 'flag-om': 'Oman', 'flag-pk': 'Pakistan',
  'flag-pw': 'Palau', 'flag-ps': 'Palestine', 'flag-pa': 'Panama', 'flag-pg': 'Papua New Guinea',
  'flag-py': 'Paraguay', 'flag-pe': 'Peru', 'flag-ph': 'Philippines', 'flag-pl': 'Poland',
  'flag-pt': 'Portugal', 'flag-qa': 'Qatar', 'flag-ro': 'Romania', 'flag-ru': 'Russia',
  'flag-rw': 'Rwanda', 'flag-kn': 'Saint Kitts Nevis', 'flag-lc': 'Saint Lucia', 'flag-vc': 'Saint Vincent Grenadines',
  'flag-ws': 'Samoa', 'flag-sm': 'San Marino', 'flag-st': 'Sao Tome Principe', 'flag-sa': 'Saudi Arabia',
  'flag-sn': 'Senegal', 'flag-rs': 'Serbia', 'flag-sc': 'Seychelles', 'flag-sl': 'Sierra Leone',
  'flag-sg': 'Singapore', 'flag-sk': 'Slovakia', 'flag-si': 'Slovenia', 'flag-sb': 'Solomon Islands',
  'flag-so': 'Somalia', 'flag-za': 'South Africa', 'flag-ss': 'South Sudan', 'flag-es': 'Spain Espana',
  'flag-lk': 'Sri Lanka', 'flag-sd': 'Sudan', 'flag-sr': 'Suriname', 'flag-se': 'Sweden',
  'flag-ch': 'Switzerland Swiss', 'flag-sy': 'Syria', 'flag-tw': 'Taiwan', 'flag-tj': 'Tajikistan',
  'flag-tz': 'Tanzania', 'flag-th': 'Thailand', 'flag-tl': 'Timor-Leste East Timor', 'flag-tg': 'Togo',
  'flag-to': 'Tonga', 'flag-tt': 'Trinidad Tobago', 'flag-tn': 'Tunisia', 'flag-tr': 'Turkey Turkiye',
  'flag-tm': 'Turkmenistan', 'flag-tv': 'Tuvalu', 'flag-ug': 'Uganda', 'flag-ua': 'Ukraine',
  'flag-ae': 'United Arab Emirates UAE Dubai', 'flag-gb': 'United Kingdom UK Britain England Scotland Wales',
  'flag-us': 'United States USA America', 'flag-uy': 'Uruguay', 'flag-uz': 'Uzbekistan', 'flag-vu': 'Vanuatu',
  'flag-va': 'Vatican', 'flag-ve': 'Venezuela', 'flag-vn': 'Vietnam', 'flag-ye': 'Yemen',
  'flag-zm': 'Zambia', 'flag-zw': 'Zimbabwe'
};

// Helper function to get emoji for an avatar ID
export const getAvatarEmoji = (avatarId) => AVATAR_EMOJIS[avatarId] || '⭐';

// Get all unique categories
export const getAvatarCategories = () => [...new Set(AVATARS.map(a => a.category))];

// Get avatars by category
export const getAvatarsByCategory = (category) => AVATARS.filter(a => a.category === category);
