/**
 * Learn-mode language registry (~224 languages).
 *
 * GENERATED from the platform's Unicode/CLDR data (Intl.DisplayNames under Node,
 * which ships full ICU) and baked in, so coverage and native autonyms are
 * identical in every browser regardless of the browser's own ICU data.
 * SPECIFIC languages, never macro 'zh': Mandarin (cmn, Simplified) and Cantonese
 * (yue, Traditional) are distinct. Ordered by rough global demand.
 */
export const LANGUAGES = [
  { code: "en", native: "English", english: "English" },
  { code: "cmn", native: "普通话", english: "Mandarin Chinese" },
  { code: "hi", native: "हिन्दी", english: "Hindi" },
  { code: "es", native: "español", english: "Spanish" },
  { code: "ar", native: "العربية", english: "Arabic", rtl: true },
  { code: "bn", native: "বাংলা", english: "Bangla" },
  { code: "pt", native: "português", english: "Portuguese" },
  { code: "ru", native: "русский", english: "Russian" },
  { code: "ja", native: "日本語", english: "Japanese" },
  { code: "pa", native: "ਪੰਜਾਬੀ", english: "Punjabi" },
  { code: "de", native: "Deutsch", english: "German" },
  { code: "jv", native: "Jawa", english: "Javanese" },
  { code: "ko", native: "한국어", english: "Korean" },
  { code: "fr", native: "français", english: "French" },
  { code: "te", native: "తెలుగు", english: "Telugu" },
  { code: "mr", native: "मराठी", english: "Marathi" },
  { code: "tr", native: "Türkçe", english: "Turkish" },
  { code: "ta", native: "தமிழ்", english: "Tamil" },
  { code: "vi", native: "Tiếng Việt", english: "Vietnamese" },
  { code: "yue", native: "粵語", english: "Cantonese" },
  { code: "ur", native: "اردو", english: "Urdu", rtl: true },
  { code: "it", native: "italiano", english: "Italian" },
  { code: "th", native: "ไทย", english: "Thai" },
  { code: "gu", native: "ગુજરાતી", english: "Gujarati" },
  { code: "fa", native: "فارسی", english: "Persian", rtl: true },
  { code: "pl", native: "polski", english: "Polish" },
  { code: "uk", native: "українська", english: "Ukrainian" },
  { code: "ms", native: "Melayu", english: "Malay" },
  { code: "kn", native: "ಕನ್ನಡ", english: "Kannada" },
  { code: "or", native: "ଓଡ଼ିଆ", english: "Odia" },
  { code: "ml", native: "മലയാളം", english: "Malayalam" },
  { code: "my", native: "မြန်မာ", english: "Burmese" },
  { code: "su", native: "Basa Sunda", english: "Sundanese" },
  { code: "ha", native: "Hausa", english: "Hausa" },
  { code: "fil", native: "Filipino", english: "Filipino" },
  { code: "am", native: "አማርኛ", english: "Amharic" },
  { code: "ne", native: "नेपाली", english: "Nepali" },
  { code: "si", native: "සිංහල", english: "Sinhala" },
  { code: "km", native: "ខ្មែរ", english: "Khmer" },
  { code: "lo", native: "ລາວ", english: "Lao" },
  { code: "el", native: "Ελληνικά", english: "Greek" },
  { code: "hu", native: "magyar", english: "Hungarian" },
  { code: "cs", native: "čeština", english: "Czech" },
  { code: "ro", native: "română", english: "Romanian" },
  { code: "sv", native: "svenska", english: "Swedish" },
  { code: "yo", native: "Èdè Yorùbá", english: "Yoruba" },
  { code: "ig", native: "Igbo", english: "Igbo" },
  { code: "zu", native: "isiZulu", english: "Zulu" },
  { code: "az", native: "azərbaycan", english: "Azerbaijani" },
  { code: "uz", native: "o‘zbek", english: "Uzbek" },
  { code: "kk", native: "қазақ тілі", english: "Kazakh" },
  { code: "ps", native: "پښتو", english: "Pashto", rtl: true },
  { code: "as", native: "অসমীয়া", english: "Assamese" },
  { code: "mai", native: "मैथिली", english: "Maithili" },
  { code: "bho", native: "भोजपुरी", english: "Bhojpuri" },
  { code: "sd", native: "سنڌي", english: "Sindhi", rtl: true },
  { code: "ckb", native: "کوردیی ناوەندی", english: "Central Kurdish", rtl: true },
  { code: "so", native: "Soomaali", english: "Somali" },
  { code: "rw", native: "Ikinyarwanda", english: "Kinyarwanda" },
  { code: "nan", native: "閩南語", english: "Hokkien (Min Nan)" },
  { code: "hak", native: "Hakka Chinese", english: "Hakka Chinese" },
  { code: "wuu", native: "Wu Chinese", english: "Wu Chinese" },
  { code: "hsn", native: "Xiang Chinese", english: "Xiang Chinese" },
  { code: "nl", native: "Nederlands", english: "Dutch" },
  { code: "da", native: "dansk", english: "Danish" },
  { code: "no", native: "norsk", english: "Norwegian" },
  { code: "fi", native: "suomi", english: "Finnish" },
  { code: "sk", native: "slovenčina", english: "Slovak" },
  { code: "sl", native: "slovenščina", english: "Slovenian" },
  { code: "hr", native: "hrvatski", english: "Croatian" },
  { code: "sr", native: "српски", english: "Serbian" },
  { code: "bs", native: "bosanski", english: "Bosnian" },
  { code: "bg", native: "български", english: "Bulgarian" },
  { code: "lt", native: "lietuvių", english: "Lithuanian" },
  { code: "lv", native: "latviešu", english: "Latvian" },
  { code: "et", native: "eesti", english: "Estonian" },
  { code: "sq", native: "shqip", english: "Albanian" },
  { code: "mk", native: "македонски", english: "Macedonian" },
  { code: "be", native: "беларуская", english: "Belarusian" },
  { code: "ga", native: "Gaeilge", english: "Irish" },
  { code: "cy", native: "Cymraeg", english: "Welsh" },
  { code: "gd", native: "Gàidhlig", english: "Scottish Gaelic" },
  { code: "eu", native: "euskara", english: "Basque" },
  { code: "ca", native: "català", english: "Catalan" },
  { code: "gl", native: "galego", english: "Galician" },
  { code: "is", native: "íslenska", english: "Icelandic" },
  { code: "mt", native: "Malti", english: "Maltese" },
  { code: "lb", native: "Lëtzebuergesch", english: "Luxembourgish" },
  { code: "fo", native: "føroyskt", english: "Faroese" },
  { code: "oc", native: "occitan", english: "Occitan" },
  { code: "co", native: "Corsican", english: "Corsican" },
  { code: "rm", native: "rumantsch", english: "Romansh" },
  { code: "br", native: "brezhoneg", english: "Breton" },
  { code: "wa", native: "Walloon", english: "Walloon" },
  { code: "fy", native: "Frysk", english: "Western Frisian" },
  { code: "sc", native: "sardu", english: "Sardinian" },
  { code: "vec", native: "veneto", english: "Venetian" },
  { code: "lmo", native: "Lombard", english: "Lombard" },
  { code: "nap", native: "Neapolitan", english: "Neapolitan" },
  { code: "scn", native: "Sicilian", english: "Sicilian" },
  { code: "an", native: "Aragonese", english: "Aragonese" },
  { code: "ast", native: "asturianu", english: "Asturian" },
  { code: "li", native: "Limburgish", english: "Limburgish" },
  { code: "gsw", native: "Schwiizertüütsch", english: "Swiss German" },
  { code: "hsb", native: "hornjoserbšćina", english: "Upper Sorbian" },
  { code: "dsb", native: "dolnoserbšćina", english: "Lower Sorbian" },
  { code: "csb", native: "Kashubian", english: "Kashubian" },
  { code: "rue", native: "Rusyn", english: "Rusyn" },
  { code: "ky", native: "кыргызча", english: "Kyrgyz" },
  { code: "tk", native: "türkmen dili", english: "Turkmen" },
  { code: "tt", native: "татар", english: "Tatar" },
  { code: "ba", native: "Bashkir", english: "Bashkir" },
  { code: "cv", native: "чӑваш", english: "Chuvash" },
  { code: "ug", native: "ئۇيغۇرچە", english: "Uyghur", rtl: true },
  { code: "mn", native: "монгол", english: "Mongolian" },
  { code: "bo", native: "བོད་སྐད་", english: "Tibetan" },
  { code: "tg", native: "тоҷикӣ", english: "Tajik" },
  { code: "sah", native: "саха тыла", english: "Yakut" },
  { code: "kaa", native: "Kara-Kalpak", english: "Kara-Kalpak" },
  { code: "crh", native: "Crimean Tatar", english: "Crimean Tatar" },
  { code: "kum", native: "Kumyk", english: "Kumyk" },
  { code: "tyv", native: "Tuvinian", english: "Tuvinian" },
  { code: "kok", native: "कोंकणी", english: "Konkani" },
  { code: "doi", native: "डोगरी", english: "Dogri" },
  { code: "ks", native: "کٲشُر", english: "Kashmiri", rtl: true },
  { code: "sat", native: "ᱥᱟᱱᱛᱟᱲᱤ", english: "Santali" },
  { code: "mni", native: "মৈতৈলোন্", english: "Manipuri" },
  { code: "gom", native: "कोंकणी", english: "Konkani" },
  { code: "raj", native: "राजस्थानी", english: "Rajasthani" },
  { code: "mag", native: "Magahi", english: "Magahi" },
  { code: "bpy", native: "Bishnupriya", english: "Bishnupriya" },
  { code: "awa", native: "Awadhi", english: "Awadhi" },
  { code: "new", native: "Newari", english: "Newari" },
  { code: "dv", native: "Divehi", english: "Divehi", rtl: true },
  { code: "bod", native: "བོད་སྐད་", english: "Tibetan" },
  { code: "id", native: "Indonesia", english: "Indonesian" },
  { code: "ceb", native: "Cebuano", english: "Cebuano" },
  { code: "war", native: "Waray", english: "Waray" },
  { code: "ilo", native: "Iloko", english: "Iloko" },
  { code: "min", native: "Minangkabau", english: "Minangkabau" },
  { code: "ban", native: "Balinese", english: "Balinese" },
  { code: "bug", native: "Buginese", english: "Buginese" },
  { code: "mad", native: "Madurese", english: "Madurese" },
  { code: "ace", native: "Acehnese", english: "Acehnese" },
  { code: "mi", native: "Māori", english: "Māori" },
  { code: "sm", native: "Samoan", english: "Samoan" },
  { code: "to", native: "lea fakatonga", english: "Tongan" },
  { code: "fj", native: "Fijian", english: "Fijian" },
  { code: "haw", native: "ʻŌlelo Hawaiʻi", english: "Hawaiian" },
  { code: "ty", native: "Tahitian", english: "Tahitian" },
  { code: "mg", native: "Malagasy", english: "Malagasy" },
  { code: "pam", native: "Pampanga", english: "Pampanga" },
  { code: "bcl", native: "Bikol", english: "Bikol" },
  { code: "hil", native: "Hiligaynon", english: "Hiligaynon" },
  { code: "pag", native: "Pangasinan", english: "Pangasinan" },
  { code: "shn", native: "Shan", english: "Shan" },
  { code: "kha", native: "Khasi", english: "Khasi" },
  { code: "ii", native: "ꆈꌠꉙ", english: "Sichuan Yi" },
  { code: "sw", native: "Kiswahili", english: "Swahili" },
  { code: "xh", native: "IsiXhosa", english: "Xhosa" },
  { code: "st", native: "Sesotho", english: "Southern Sotho" },
  { code: "tn", native: "Setswana", english: "Tswana" },
  { code: "ts", native: "Tsonga", english: "Tsonga" },
  { code: "ss", native: "Swati", english: "Swati" },
  { code: "ve", native: "Venda", english: "Venda" },
  { code: "nr", native: "South Ndebele", english: "South Ndebele" },
  { code: "nso", native: "Sesotho sa Leboa", english: "Northern Sotho" },
  { code: "om", native: "Oromoo", english: "Oromo" },
  { code: "ti", native: "ትግርኛ", english: "Tigrinya" },
  { code: "rn", native: "Ikirundi", english: "Rundi" },
  { code: "lg", native: "Luganda", english: "Ganda" },
  { code: "ny", native: "Nyanja", english: "Nyanja" },
  { code: "sn", native: "chiShona", english: "Shona" },
  { code: "ff", native: "Pulaar", english: "Fula" },
  { code: "wo", native: "Wolof", english: "Wolof" },
  { code: "ln", native: "lingála", english: "Lingala" },
  { code: "kg", native: "Kongo", english: "Kongo" },
  { code: "lu", native: "Tshiluba", english: "Luba-Katanga" },
  { code: "bm", native: "bamanakan", english: "Bambara" },
  { code: "ee", native: "eʋegbe", english: "Ewe" },
  { code: "tw", native: "Akan", english: "Akan" },
  { code: "ak", native: "Akan", english: "Akan" },
  { code: "sg", native: "Sängö", english: "Sango" },
  { code: "kr", native: "Kanuri", english: "Kanuri" },
  { code: "kab", native: "Taqbaylit", english: "Kabyle" },
  { code: "shi", native: "ⵜⴰⵛⵍⵃⵉⵜ", english: "Tachelhit" },
  { code: "tzm", native: "Tamaziɣt n laṭlaṣ", english: "Central Atlas Tamazight" },
  { code: "kln", native: "Kalenjin", english: "Kalenjin" },
  { code: "luy", native: "Luluhia", english: "Luyia" },
  { code: "kam", native: "Kikamba", english: "Kamba" },
  { code: "guz", native: "Ekegusii", english: "Gusii" },
  { code: "mer", native: "Kĩmĩrũ", english: "Meru" },
  { code: "ebu", native: "Kĩembu", english: "Embu" },
  { code: "dav", native: "Kitaita", english: "Taita" },
  { code: "saq", native: "Kisampur", english: "Samburu" },
  { code: "teo", native: "Kiteso", english: "Teso" },
  { code: "mas", native: "Maa", english: "Masai" },
  { code: "nyn", native: "Runyankore", english: "Nyankole" },
  { code: "cgg", native: "Rukiga", english: "Chiga" },
  { code: "xog", native: "Olusoga", english: "Soga" },
  { code: "gaa", native: "Gã", english: "Ga" },
  { code: "dyo", native: "joola", english: "Jola-Fonyi" },
  { code: "mos", native: "Mossi", english: "Mossi" },
  { code: "dje", native: "Zarmaciine", english: "Zarma" },
  { code: "twq", native: "Tasawaq senni", english: "Tasawaq" },
  { code: "bem", native: "Ichibemba", english: "Bemba" },
  { code: "umb", native: "Umbundu", english: "Umbundu" },
  { code: "kmb", native: "Kimbundu", english: "Kimbundu" },
  { code: "he", native: "עברית", english: "Hebrew", rtl: true },
  { code: "ku", native: "kurdî (kurmancî)", english: "Kurdish" },
  { code: "prs", native: "دری", english: "Dari", rtl: true },
  { code: "ka", native: "ქართული", english: "Georgian" },
  { code: "hy", native: "հայերեն", english: "Armenian" },
  { code: "qu", native: "Runasimi", english: "Quechua" },
  { code: "gn", native: "Guarani", english: "Guarani" },
  { code: "ay", native: "Aymara", english: "Aymara" },
  { code: "nv", native: "Navajo", english: "Navajo" },
  { code: "ht", native: "Haitian Creole", english: "Haitian Creole" },
  { code: "jam", native: "Jamaican Creole English", english: "Jamaican Creole English" },
  { code: "pap", native: "Papiamento", english: "Papiamento" },
  { code: "srn", native: "Sranan Tongo", english: "Sranan Tongo" },
  { code: "eo", native: "Esperanto", english: "Esperanto" },
  { code: "yi", native: "ייִדיש", english: "Yiddish", rtl: true },
  { code: "la", native: "Latin", english: "Latin" },
];

export const LANGUAGE_CODES = LANGUAGES.map(l => l.code);
export const RTL_SET = new Set(LANGUAGES.filter(l => l.rtl).map(l => l.code));

export function isRTL(code) {
  return RTL_SET.has(code);
}

export default LANGUAGES;
